MODULE KINDS

        INTEGER, PARAMETER :: DP = KIND(0.0D0)
        INTEGER, PARAMETER :: DP_SIZE  = 8

        INTEGER, PARAMETER :: SG = KIND(0.0)
        INTEGER, PARAMETER :: SG_SIZE = 4

END MODULE KINDS
